### ISSUE TITLE
msh3reach in addition to quicreach

### ISSUE THREAD

**Issue by davinci26** [microsoft/quicreach#34]
I can also do this outside of the repo but I can also add this into the repro if you are interested. It fits kind of loosely to the scope of the repo.

Basically quicreach since it only does the QUIC handshake doesnt know if the server actually advertises quic. This means that if you are hooked into a CDN provider you might have quic enabled on your IP pool but dont advertise it.

So concretely the recommendation here would be to use https://github.com/nibanks/msh3  and try out all the domains that can do the QUIC handshake and inspect the `alt-svc` header to see if they advertise h3.

**Comment by nibanks** [comment]
As much as I'd like it to me, msh3 isn't officially supported by MSFT right now (only a pet project of mine). So, we can't create an msh3reach here, or in the microsoft organization currently. I would support you, or someone else, essentially copy/pasting this project and creating an msh3reach on top of msh3. I would definitely star it, and help out as I can.

**Comment by nibanks** [comment]
Maybe you could submodule this repo to share the domains.hpp file.

**Comment by davinci26** [comment]
Makes sense, thanks for considering!

Would you be interested in this feature regardless of using msh3? If you were interested in the data then any http library could be used to do this. We dont even have to do an HTTP3 connection to see the value of the Alt-Svc header.

Otherwise, I can always implement this on my fork of the repo :)

(btw compiled curl with http3 with msh3 and msquic and it works like a charm, nice job!)

**Comment by nibanks** [comment]
> Would you be interested in this feature regardless of using msh3? If you were interested in the data then any http library could be used to do this. We dont even have to do an HTTP3 connection to see the value of the Alt-Svc header.

Yes it might be interesting to know which hosts are advertising HTTP/3, but I don't think this project is the right place for that.

> (btw compiled curl with http3 with msh3 and msquic and it works like a charm, nice job!)

Thanks!

I'm going to close this issue since it's been decided we won't add anything to quicreach for this.
